python dist test builds

diff --git a/test/dist/python/action/win/action.yml b/test/dist/python/action/win/action.yml
--- a/test/dist/python/action/win/action.yml
+++ b/test/dist/python/action/win/action.yml
@@ -19,12 +19,21 @@ runs:
     with:
       python-version: '${{ inputs.python_version }}'
       architecture: ${{ inputs.arch }}
+  - name: Find Wheel File
+    shell: powershell
+    run: |
+      $pattern = "${{ inputs.wheel_filename }}"
+      $file = Get-ChildItem $pattern | Select-Object -First 1
+      if ($null -eq $file) {
+        Write-Error "Wheel file not found"
+        exit 1
+      }
+      echo "WHEEL_FILENAME=$file" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+
   - name: pip3
     working-directory: artifacts/distfiles
     run: |
-      echo ${{ inputs.wheel_filename }}
-      dir ${{ inputs.wheel_filename }}
-      python -m pip install ${{ inputs.wheel_filename }}
+      python -m pip install ${{ env.WHEEL_FILENAME }}
     shell: cmd
   - name: test
     run: |
